title: Simon's personal website!
email: si.younguk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A website about me, Simon Young and my work.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://siyounguk.github.io" # the base hostname & protocol for your site
twitter_username: siyounguk
github_username:  siyounguk
exclude: ['README.md', 'GEMFILE', 'GEMFILE.lock']

# Build settings
markdown: kramdown
